[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "newsapi-python>=0.2.7",
    "numpy",
    "openai>=1.98.0",
    "pandas",
    "requests",
    "streamlit>=1.47.1",
    "yfinance",
]
